Request for review from Uchenna Anya
henatan99/apple-main-webpage- pull request #1
Opened 2020-09-29 19:32 UTC by uchennaanya

The features of this project are listed below:

1. Have a nav section
   - With embedded images and videos
   - With an embedded section with grid layout
2. Have a Promo section
   - Promo Pictures
3. Apple Page nav section
   - Nav links to many other pages aligned in a flex row direction
4. Has a footer with
   - Nav links to Legal, Privacy, and Security
   - Copy right information statement

2020-09-29 20:24 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @uchennaanya & @henatan99,

__I must say, you've done an amazing job so far. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] The main background image is not rending in your live project: all I can see here is a blank background. Kindly check it out and make your background render in production.

Here's what I have here:
![21:13:03](https://user-images.githubusercontent.com/26856491/94610691-94394d80-0298-11eb-9d90-eafff89ce101.png)

- [ ] The footer elements (images) should be linked. 
![21:14:22](https://user-images.githubusercontent.com/26856491/94610815-c3e85580-0298-11eb-9d5b-92c921a35163.png)

- [ ] I made some comments below about your readme file. Please check those comments and others, then make necessary corrections.

**[ OPTIONAL CHANGES ]**

- [ ] Your background gradient color seems to be a little bit different from the original. Kindly try to change it so it matches the original gradient color
Original page:
![21:17:39](https://user-images.githubusercontent.com/26856491/94611294-71f3ff80-0299-11eb-9cd2-1b19cd778946.png)

Your page:
![21:15:18](https://user-images.githubusercontent.com/26856491/94611311-76b8b380-0299-11eb-9c9f-3e1ee4c39019.png)


**[ COMMENTS ]**

- [ ] It looks like you're working on this branch after submitting the review request. 
- To get the best and updated review, always finalize your work before requesting for review.
- Avoid pushing to the same branch after submitting your review request. You can always improve and push commits to the project after receiving your feedback from the review process.

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-09-29 20:24 UTC, teekaytech commented on README.md
> +
This section of the readme should be removed. It looks like a duplicate of what you have on line 11.

2020-09-29 20:24 UTC, teekaytech commented on README.md
> +
Something seems to be wrong with the arrangement of this section. Kindly observe carefully and fix it.
- For instance, you mentioned inline 47 that we should follow some steps whereas the steps are not mentioned.
- Also on line 49, if that is a header, then let it be styled like a header, then add the content. Else, you should remove it if it has no content.

2020-09-29 20:24 UTC, teekaytech commented on index.html
> +        </figure>
Each of these items (images) should be linked. Kindly wrap it around the `<a>` tag. 
![21:01:37](https://user-images.githubusercontent.com/26856491/94609640-fbee9900-0296-11eb-88d8-2051ac003218.png)

2020-09-30 06:36 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Everything is looking good in this project, except for the fact that you still have some changes that are required to be fixed before this project can be approved. Let's check them out below:__

**[ REQUIRED CHANGES ]**

- [ ] Your main background image is still not rending in your live project. Please try to identify the cause of this bug and fix it. You can use GitHub Pages as an alternative to using githack. See how [here](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-09-30 06:36 UTC, teekaytech commented on README.md
>  # apple-main-webpage-
The project title has already been re-defined in line 6 below. To avoid repetition, kindly remove it.

2020-09-30 07:50 UTC, arslanbisharat approved these changes
## Approved 
Thank you for making all the changes requested by previous TSEs.
Please merge the branch and move forward with your curriculum.
**Arslan Bisharat**

2020-09-30 07:56 UTC, merged